
version = 1

[install]
python312.pkg-path = "python312"
conda.pkg-path = "python312Packages.conda"
pip.pkg-path = "python312Packages.pip"

[vars]

[hook]

[profile]

[services]

## Other Environment Options -----------------------------------------
[options]

systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
