
version = 1

[install]
#python3.pkg-path = "python312" # python is now installed via conda
#conda.pkg-path = "python312Packages.conda"
#pip.pkg-path = "python312Packages.pip"
conda.pkg-path = "conda"
conda.systems = ["aarch64-linux", "x86_64-linux"]
gcc.pkg-path = "gcc"
gnumake.pkg-path = "gnumake"
go.pkg-path = "go"
#pip.pkg-path = "python312Packages.pip"
binutils.pkg-path = "binutils"
zlib.pkg-path = "zlib"

fhs.flake = "path:./flakes/fhs"

[vars]

[hook]

[profile]

[services]

## Other Environment Options -----------------------------------------
[options]

systems = [
  #  "aarch64-darwin",
  "aarch64-linux", #  "x86_64-darwin",
  "x86_64-linux",
]
